### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by Uzaaft** [calumrussell/alator#30]
I'm considering using this project in my own projects. Is it possible to add a licence to the project to know if it's viable for me to use it?

**Comment by calumrussell** [comment]
> I'm considering using this project in my own projects. Is it possible to add a licence to the project to know if it's viable for me to use it?

Will do this now.

**Comment by Uzaaft** [comment]
Fixed in 5e3d5b1eee45098af7d7a6fd368e1b4c859880ed

**Comment by calumrussell** [comment]
Is MIT good for you? This is just a backend for me so have no issues with any kind of third-party commercial usage.
